# Generated by Django 4.1.4 on 2022-12-24 10:19

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Горный Хребет')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='MountainPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('title_2', models.CharField(max_length=150, null=True, verbose_name='Альтернативное название')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('height', models.IntegerField(verbose_name='Высота')),
                ('photos', models.FileField(blank=True, upload_to='files/', verbose_name='Фото')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending', 'В процессе'), ('accepted', 'Модерация прошла'), ('rejected', 'Модерация не прошла')], default='new', max_length=200, verbose_name='Статус')),
                ('dl_spring', models.CharField(blank=True, choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=2, verbose_name='Уровень сложности весной')),
                ('dl_summer', models.CharField(blank=True, choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=2, verbose_name='Уровень сложности летом')),
                ('dl_autumn', models.CharField(blank=True, choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=2, verbose_name='Уровень сложности осенью')),
                ('dl_winter', models.CharField(blank=True, choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=2, verbose_name='Уровень сложности зимой')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.area', verbose_name='Горный хребет')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user')),
            ],
        ),
    ]
